MAIN_DIR = src
TEST_DIR = test

.PHONY: main test

all: main test

main:
	
test:

clean:

run-main:
	
run-test:
	@echo "[{\"methodName\":\"genericTest\",\"pointNames\": [\"7.1\", \"7.2\", \"7.3\"], \"status\": \"PASSED\", \"message\": \"\"}]" > test_output.txt
	
get-points:
	@echo "foo\nbar\nbash\n7.1\n7.2\n7.3\n"
