MAIN_DIR = src
TEST_DIR = test

.PHONY: main test

all: main test

main:
	# @echo "1" > points.txt
	# @echo "1" > tmc_available_points.txt
	
test:
        @echo "1"
	# @echo "1" > tmc_available_points.txt
clean:
	rm -f tmc_available_points.txt points.txt

run-main:
	#@echo "1" > points.txt
	#@echo "1" > tmc_available_points.txt
	
run-test:
	#@echo "1" > points.txt
	#@echo "1" > tmc_available_points.txt
	
get-points:
	@echo "foo\nbar\nbash\n1\n2"
	
