MAIN_DIR = src
TEST_DIR = test

.PHONY: main test

all: main test

main:
	
test:

clean:

run-main:
	
run-test:
	@echo "[{\"methodName\":\"genericTest\",\"pointNames\": [\"55.1\",\"55.2\",\"55.3\",\"55.4\"], \"status\": \"PASSED\", \"message\": \"\"}]" > test_output.txt
	
get-points:
	@echo "foo\nbar\nbash\n55.1\n55.2\n55.3\n55.4\n"
