MAIN_DIR = src
TEST_DIR = test

.PHONY: main test

all: main test

main:
	
test:

clean:

run-main:
	
run-test:
	@echo "[{\"methodName\":\"genericTest\",\"pointNames\": [\"44.1\",\"44.2\",\"44.3\"], \"status\": \"PASSED\", \"message\": \"\"}]" > test_output.txt
	
get-points:
	@echo "foo\nbar\nbash\n44.1\n44.2\n44.3\n"
