MAIN_DIR = src
TEST_DIR = test

.PHONY: main test

all: main test

main:
	
test:

clean:

run-main:
	
run-test:
	@echo "[{\"methodName\":\"genericTest\",\"pointNames\": [\"8.1\",\"8.2\",\"8.3\"], \"status\": \"PASSED\", \"message\": \"\"}]" > test_output.txt
	
get-points:
	@echo "foo\nbar\nbash\n8.1\n8.2\n8.3\n\n"
